---
title: "Correlation analysis"
author: "Bin Li"
date: "2020-04-03"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


## Load packages
```{r}
rm(list=ls())
#library(data.table)
#library(reshape2)
#library(ggplot2)

library(dplyr)
library(tidyr)
library(pheatmap)
library(RColorBrewer)
```


```{r}
pheno.file = "~/Box/Miami_IMPC/data/v10.1/AllBehaviourControls.Rdata"
load(file=pheno.file)
head(df)

pheno = df %>% filter(data_type!="TEXT") %>% 
  mutate(proc_short_name=recode(procedure_name, "Acoustic Startle and Pre-pulse Inhibition (PPI)"="PPI",
         "Combined SHIRPA and Dysmorphology"="SHIRPA",
         "Fear Conditioning"="FEAR",
         "Grip Strength"="GRIP",
         "Hole-board Exploration"="HB",
         "Light-Dark Test"="LD",
         "Open Field"="OF",
         "Rotarod"="RT",
         "Tail Suspension"="TS")) %>%
  mutate(proc_param_name=paste0(proc_short_name,"_",parameter_name))
head(pheno)

dim(pheno)
```

## Heatmap showing measured phenotype
```{r, fig.width=6, fig.height=8}

mtest = table(pheno$biological_sample_id, pheno$proc_param_name)
mtest = as.data.frame.matrix(mtest)
pheatmap(mtest, cluster_row = F, cluster_cols = F, show_rownames = F, color = brewer.pal(n = 9, name = "Reds"))

```



